  Running command git clone --quiet https://github.com/huggingface/peft.git /tmp/pip-install-un_ufxhq/peft_d7925ab10c334210aa8568a613553bbf
  Running command git clone --quiet https://github.com/huggingface/accelerate.git /tmp/pip-install-un_ufxhq/accelerate_36eea04f96fd4db0960deb47729ab225
/home/brc4cb/.conda/envs/falcon_40B/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/home/brc4cb/.conda/envs/falcon_40B/lib/libcudart.so.11.0'), PosixPath('/home/brc4cb/.conda/envs/falcon_40B/lib/libcudart.so')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
/home/brc4cb/.conda/envs/falcon_40B/lib/python3.9/getpass.py:91: GetPassWarning: Can not control echo on the terminal.
  passwd = fallback_getpass(prompt, stream)
Warning: Password input may be echoed.
Token: Traceback (most recent call last):
  File "/home/brc4cb/.conda/envs/falcon_40B/lib/python3.9/getpass.py", line 69, in unix_getpass
    old = termios.tcgetattr(fd)     # a copy to save
termios.error: (25, 'Inappropriate ioctl for device')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gpfs/gpfs0/project/SDS/research/christ_research/guanaco/llama-65b/text_classifier.py", line 50, in <module>
    login(token = token)
  File "/home/brc4cb/.conda/envs/falcon_40B/lib/python3.9/site-packages/huggingface_hub/_login.py", line 100, in login
    interpreter_login(new_session=new_session, write_permission=write_permission)
  File "/home/brc4cb/.conda/envs/falcon_40B/lib/python3.9/site-packages/huggingface_hub/_login.py", line 161, in interpreter_login
    token = getpass("Token: ")
  File "/home/brc4cb/.conda/envs/falcon_40B/lib/python3.9/getpass.py", line 91, in unix_getpass
    passwd = fallback_getpass(prompt, stream)
  File "/home/brc4cb/.conda/envs/falcon_40B/lib/python3.9/getpass.py", line 126, in fallback_getpass
    return _raw_input(prompt, stream)
  File "/home/brc4cb/.conda/envs/falcon_40B/lib/python3.9/getpass.py", line 148, in _raw_input
    raise EOFError
EOFError
